title: Deneb
author: Ankit R Gadiya
author-img: avatar.svg  # In /assets/images/ dir
cover: https://raw.githubusercontent.com/ankitrgadiya/deneb/master/assets/images/background.jpg

lang: "en"
google_verification: J0CD-ynr2w5EhpI_VrP-OOrThFQcJyRyTnWTWz2dfgU

paginate: 5
paginate_path: "/page:num/"

gems: [jekyll-paginate]
